# Generated by Django 3.0.2 on 2020-02-05 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enduser', models.CharField(max_length=255, verbose_name='E/U')),
                ('hansha', models.CharField(blank=True, max_length=255, verbose_name='販社')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jutyu', models.DateField(blank=True, verbose_name='受注時期')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cms.Anken', verbose_name='案件')),
            ],
        ),
    ]
