# Generated by Django 3.0.2 on 2020-02-10 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20200207_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shosaijouhou',
            fields=[
                ('anken', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cms.Anken')),
                ('kakudo', models.CharField(blank=True, max_length=255, verbose_name='確度')),
                ('kyougou', models.CharField(blank=True, max_length=255, verbose_name='競合')),
            ],
        ),
        migrations.AlterField(
            model_name='anken',
            name='hansha',
            field=models.CharField(max_length=255, verbose_name='販社'),
        ),
        migrations.AlterField(
            model_name='anken',
            name='product',
            field=models.CharField(max_length=255, verbose_name='プロダクト'),
        ),
        migrations.AlterField(
            model_name='anken',
            name='sisuisin',
            field=models.CharField(max_length=255, verbose_name='SI推進'),
        ),
        migrations.AlterField(
            model_name='sintyoku',
            name='sintyoku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sintyokus', to='cms.Anken', verbose_name='案件'),
        ),
    ]
