# Generated by Django 3.0.2 on 2020-02-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20200210_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='anken',
            name='kakudo',
            field=models.CharField(blank=True, max_length=255, verbose_name='確度'),
        ),
        migrations.AddField(
            model_name='anken',
            name='kyougou',
            field=models.CharField(blank=True, max_length=255, verbose_name='競合'),
        ),
        migrations.DeleteModel(
            name='Shosaijouhou',
        ),
    ]
