# Generated by Django 3.0.2 on 2020-02-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_auto_20200210_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='anken',
            name='kousinjikoku',
            field=models.DateField(auto_now=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='anken',
            name='donyu',
            field=models.DateField(blank=True, verbose_name='導入時期'),
        ),
        migrations.AlterField(
            model_name='anken',
            name='jutyu',
            field=models.DateField(blank=True, verbose_name='受注時期'),
        ),
    ]
