# Generated by Django 3.0.2 on 2020-02-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20200214_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='anken',
            name='donyusien',
            field=models.CharField(blank=True, max_length=255, verbose_name='導入支援'),
        ),
        migrations.AddField(
            model_name='anken',
            name='hitouch',
            field=models.CharField(blank=True, max_length=255, verbose_name='ハイタッチ担当'),
        ),
        migrations.AddField(
            model_name='anken',
            name='sbkk',
            field=models.CharField(blank=True, max_length=255, verbose_name='SBKKトスアップ'),
        ),
        migrations.AlterField(
            model_name='anken',
            name='arari',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='粗利額'),
        ),
        migrations.AlterField(
            model_name='anken',
            name='mitumorigaku',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='見積もり金額'),
        ),
    ]
