# Generated by Django 3.0.2 on 2020-02-07 07:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20200205_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sintyoku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kinyubi', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='記入日')),
                ('shosai', models.TextField(blank=True, verbose_name='進捗内容')),
                ('sintyoku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cms.Anken', verbose_name='案件')),
            ],
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
