# Generated by Django 3.0.2 on 2020-02-21 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_auto_20200214_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanryoflg', models.BooleanField(default=False, verbose_name='')),
                ('task', models.TextField(blank=True, verbose_name='タスク')),
                ('kigen', models.DateField(blank=True, verbose_name='期限')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='cms.Anken', verbose_name='案件')),
            ],
        ),
    ]
