# Generated by Django 3.0.2 on 2020-03-05 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kanryoflg', models.BooleanField(default=False, verbose_name='')),
                ('task', models.TextField(blank=True, verbose_name='タスク')),
                ('kigen', models.DateField(blank=True, verbose_name='期限')),
                ('tantou', models.CharField(blank=True, max_length=255, verbose_name='担当')),
                ('anken', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cms.Anken', verbose_name='案件')),
            ],
        ),
    ]
